import { TranscodingProfile, VideoCodec, AudioCodec, Protocol } from './types';

export const DEFAULT_PROFILES: TranscodingProfile[] = [
  {
    id: 'dvb-h264-1080i50-cbr',
    name: 'DVB-T2/C: H.264 1080i50 CBR (MP2 48kHz)',
    videoCodec: VideoCodec.H264,
    audioCodec: AudioCodec.MP2,
    resolution: '1920x1080',
    videoQualityMode: 'cbr',
    rateControl: 'cbr',
    videoBitrate: 6000,
    minrate: 6000,
    maxrate: 6000,
    bufsize: 12000,
    audioBitrate: 192,
    sampleRate: 48000,
    audioChannels: 2,
    preset: 'medium',
    framerate: 50,
    fpsMode: 'cfr',
    gopSize: 50,
    bFrames: 2,
    cabac: true,
    avcProfile: 'high',
    avcLevel: '4.1',
    interlaced: true,
    scaleInterpolation: 'bicubic',
    aspectRatio: '16:9',
    pixelFormat: 'yuv420p',
    videoEnabled: true,
    audioEnabled: true,
    accelerate: false,
  },
  {
    id: 'dvb-hevc-1080p50-cbr',
    name: 'DVB-T2/IPTV: H.265/HEVC 1080p50 CBR',
    videoCodec: VideoCodec.H265,
    audioCodec: AudioCodec.AAC,
    resolution: '1920x1080',
    videoQualityMode: 'cbr',
    rateControl: 'cbr',
    videoBitrate: 4500,
    minrate: 4500,
    maxrate: 4500,
    bufsize: 9000,
    audioBitrate: 192,
    sampleRate: 48000,
    audioChannels: 2,
    preset: 'medium',
    tune: 'hq',
    framerate: 50,
    fpsMode: 'cfr',
    gopSize: 50,
    bFrames: 2,
    aspectRatio: '16:9',
    pixelFormat: 'yuv420p',
    videoEnabled: true,
    audioEnabled: true,
    accelerate: false,
  },
  {
    id: 'dvb-mpeg2-pal-cbr',
    name: 'DVB Legacy: MPEG-2 576i PAL CBR (MP2 48kHz)',
    videoCodec: VideoCodec.MPEG2,
    audioCodec: AudioCodec.MP2,
    resolution: '720x576',
    videoQualityMode: 'cbr',
    rateControl: 'cbr',
    videoBitrate: 4000,
    minrate: 4000,
    maxrate: 4000,
    bufsize: 8000,
    audioBitrate: 192,
    sampleRate: 48000,
    audioChannels: 2,
    preset: 'medium',
    framerate: 25,
    fpsMode: 'cfr',
    gopSize: 12,
    bFrames: 2,
    interlaced: true,
    aspectRatio: '16:9',
    pixelFormat: 'yuv420p',
    videoEnabled: true,
    audioEnabled: true,
    accelerate: false,
  },
  {
    id: 'low-cpu-720p',
    name: 'Low CPU 720p (UDP Stable)',
    videoCodec: VideoCodec.H264,
    audioCodec: AudioCodec.AAC,
    resolution: '1280x720',
    videoQualityMode: 'bitrate',
    videoBitrate: 2000,
    audioBitrate: 128,
    sampleRate: 48000,
    preset: 'ultrafast',
    framerate: 25,
    pixelFormat: 'yuv420p',
  },
  {
    id: 'live-http-ts-1',
    name: 'HTTP-TS: 720p Low Latency',
    videoCodec: VideoCodec.H264,
    videoQualityMode: 'bitrate',
    videoBitrate: 2000,
    maxrate: 2000,
    bufsize: 4000,
    resolution: '1280x720',
    framerate: 30,
    preset: 'ultrafast',
    tune: 'zerolatency',
    pixelFormat: 'yuv420p',
    audioCodec: AudioCodec.AAC,
    audioBitrate: 128,
    sampleRate: 48000,
  },
  {
    id: 'default-h264-1080p',
    name: 'H.264 1080p (Software)',
    videoCodec: VideoCodec.H264,
    accelerate: false,
    audioCodec: AudioCodec.AAC,
    resolution: '1920x1080',
    videoQualityMode: 'bitrate',
    videoBitrate: 4000,
    audioBitrate: 128,
    sampleRate: 48000,
    preset: 'medium',
    framerate: 30,
    pixelFormat: 'yuv420p',
  },
  {
    id: 'nvidia-h264-1080p',
    name: 'H.264 1080p (NVIDIA NVENC)',
    videoCodec: VideoCodec.H264_NVENC,
    audioCodec: AudioCodec.AAC,
    resolution: '1920x1080',
    videoQualityMode: 'bitrate',
    videoBitrate: 4000,
    audioBitrate: 128,
    sampleRate: 48000,
    preset: 'p4',
    framerate: 30,
    pixelFormat: 'yuv420p',
  },
  {
    id: 'amd-h264-1080p',
    name: 'H.264 1080p (AMD AMF)',
    videoCodec: VideoCodec.H264_AMF,
    audioCodec: AudioCodec.AAC,
    resolution: '1920x1080',
    videoQualityMode: 'bitrate',
    videoBitrate: 4000,
    audioBitrate: 128,
    sampleRate: 48000,
    preset: 'p4',
    framerate: 30,
    pixelFormat: 'yuv420p',
  },
  {
    id: 'amd-hevc-1080p',
    name: 'HEVC 1080p (AMD AMF)',
    videoCodec: VideoCodec.HEVC_AMF,
    audioCodec: AudioCodec.AAC,
    resolution: '1920x1080',
    videoQualityMode: 'bitrate',
    videoBitrate: 6000,
    audioBitrate: 128,
    sampleRate: 48000,
    preset: 'p4',
    framerate: 30,
    pixelFormat: 'yuv420p',
  },
  {
    id: 'apple-h264-1080p',
    name: 'H.264 1080p (Apple VideoToolbox)',
    videoCodec: VideoCodec.H264_VIDEOTOOLBOX,
    audioCodec: AudioCodec.AAC,
    resolution: '1920x1080',
    videoQualityMode: 'bitrate',
    videoBitrate: 4000,
    audioBitrate: 128,
    sampleRate: 48000,
    preset: 'ultrafast',
    framerate: 30,
    pixelFormat: 'yuv420p',
  },
  {
    id: 'quality-h264-crf-23',
    name: 'High-Quality H.264 (CRF 23)',
    videoCodec: VideoCodec.H264,
    audioCodec: AudioCodec.AAC,
    resolution: '1920x1080',
    videoQualityMode: 'crf',
    crf: 23,
    audioBitrate: 192,
    sampleRate: 48000,
    preset: 'medium',
    framerate: 30,
    pixelFormat: 'yuv420p',
  },
  {
    id: 'uhd-h265-4k',
    name: 'UHD HEVC 4K (Software)',
    videoCodec: VideoCodec.H265,
    accelerate: false,
    audioCodec: AudioCodec.AAC,
    resolution: '3840x2160',
    videoQualityMode: 'bitrate',
    videoBitrate: 15000,
    audioBitrate: 192,
    sampleRate: 48000,
    preset: 'medium',
    framerate: 30,
    pixelFormat: 'yuv420p',
  },
  {
    id: 'audio-only-aac',
    name: 'Audio Only (AAC 128k)',
    videoCodec: VideoCodec.Copy,
    audioCodec: AudioCodec.AAC,
    resolution: 'N/A',
    videoQualityMode: 'bitrate',
    isAudioOnly: true,
    audioBitrate: 128,
    sampleRate: 48000,
  },
  {
    id: 'passthrough-copy',
    name: 'Passthrough (Stream Copy)',
    videoCodec: VideoCodec.Copy,
    audioCodec: AudioCodec.Copy,
    resolution: 'N/A',
    videoQualityMode: 'bitrate',
  },
];

export const VIDEO_CODEC_OPTIONS = [
  { value: 'header-software', label: '--- Software / CPU ---', disabled: true },
  { value: VideoCodec.H264, label: 'H.264 / AVC (libx264)' },
  { value: VideoCodec.H265, label: 'H.265 / HEVC (libx265)' },
  { value: VideoCodec.MPEG2, label: 'MPEG-2 Video (DVB Broadcast Standard)' },
  { value: VideoCodec.AV1, label: 'AV1 (libaom-av1)' },
  { value: VideoCodec.VP9, label: 'VP9 (libvpx-vp9)' },
  { value: 'header-nvidia', label: '--- NVIDIA (NVENC Acceleration) ---', disabled: true },
  { value: VideoCodec.H264_NVENC, label: 'H.264 (h264_nvenc)' },
  { value: VideoCodec.HEVC_NVENC, label: 'H.265 / HEVC (hevc_nvenc)' },
  { value: 'header-intel', label: '--- Intel (QuickSync / QSV) ---', disabled: true },
  { value: VideoCodec.H264_QSV, label: 'H.264 (h264_qsv)' },
  { value: VideoCodec.HEVC_QSV, label: 'H.265 / HEVC (hevc_qsv)' },
  { value: VideoCodec.MPEG2_QSV, label: 'MPEG-2 (mpeg2_qsv)' },
  { value: 'header-amd', label: '--- AMD (AMF Hardware) ---', disabled: true },
  { value: VideoCodec.H264_AMF, label: 'H.264 (h264_amf)' },
  { value: VideoCodec.HEVC_AMF, label: 'H.265 / HEVC (hevc_amf)' },
  { value: 'header-apple', label: '--- Apple (VideoToolbox) ---', disabled: true },
  { value: VideoCodec.H264_VIDEOTOOLBOX, label: 'H.264 (h264_videotoolbox)' },
  { value: VideoCodec.HEVC_VIDEOTOOLBOX, label: 'H.265 / HEVC (hevc_videotoolbox)' },
  { value: 'header-other', label: '--- Passthrough ---', disabled: true },
  { value: VideoCodec.Copy, label: 'Copy / Passthrough (No Re-encoding)' },
];

export const AUDIO_CODEC_OPTIONS = [
  { value: AudioCodec.AAC, label: 'AAC (Advanced Audio Coding)' },
  { value: AudioCodec.MP2, label: 'MP2 (MPEG-1 Audio Layer II - DVB Broadcast Standard)' },
  { value: AudioCodec.AC3, label: 'AC-3 (Dolby Digital)' },
  { value: AudioCodec.EAC3, label: 'E-AC-3 (Dolby Digital Plus)' },
  { value: AudioCodec.MP3, label: 'MP3 (MPEG-1 Audio Layer III)' },
  { value: AudioCodec.Opus, label: 'Opus (High-Fidelity Low-Latency)' },
  { value: AudioCodec.PCM_S16LE, label: 'PCM 16-bit Uncompressed' },
  { value: AudioCodec.PCM_S24LE, label: 'PCM 24-bit Broadcast Master' },
  { value: AudioCodec.Copy, label: 'Copy / Passthrough (No Re-encoding)' },
];

export const RESOLUTION_OPTIONS = [
  { value: 'source', label: 'Same as Input (Source / Auto)' },
  { value: '3840x2160', label: '3840x2160 (4K UHD)' },
  { value: '2560x1440', label: '2560x1440 (2K QHD)' },
  { value: '1920x1080', label: '1920x1080 (Full HD 1080p)' },
  { value: '1280x720', label: '1280x720 (HD 720p)' },
  { value: '720x576', label: '720x576 (PAL 576i / DVB Standard)' },
  { value: '720x480', label: '720x480 (NTSC 480i / DVB Standard)' },
  { value: '854x480', label: '854x480 (SD 480p)' },
  { value: '640x360', label: '640x360 (Low Bandwidth)' },
];

export const LIVE_PROTOCOL_OPTIONS = [
  { value: Protocol.HLS, label: 'HLS (HTTP Live Streaming)' },
  { value: Protocol.DASH, label: 'DASH (Dynamic Adaptive Streaming)' },
  { value: Protocol.RTMP, label: 'RTMP (Real-Time Messaging Protocol)' },
  { value: Protocol.SRT, label: 'SRT (Secure Reliable Transport)' },
  { value: Protocol.UDP, label: 'UDP (Standard Raw MPEG-TS over UDP Multicast/Unicast)' },
  { value: Protocol.UDP_DVB, label: 'UDP-DVB (DVB Standard MPEG-TS with Full SI Tables / ETSI EN 300 468)' },
  { value: Protocol.HTTP_TS, label: 'HTTP-TS (MPEG-TS over HTTP)' },
  { value: Protocol.DECKLINK, label: 'DeckLink Card Output' },
  { value: Protocol.RECORDING, label: 'Recording File' },
  { value: Protocol.YOUTUBE, label: 'YouTube' },
  { value: Protocol.FACEBOOK, label: 'Facebook' },
  { value: Protocol.CUSTOM, label: 'RTMP Push' },
];

export const FRAMERATE_OPTIONS = [
  { value: '0', label: 'Original / Same as Input' },
  { value: '50', label: '50 fps (Broadcast PAL/HD Standard)' },
  { value: '59.94', label: '59.94 fps (Broadcast NTSC/HD Standard)' },
  { value: '60', label: '60 fps' },
  { value: '25', label: '25 fps (PAL Broadcast)' },
  { value: '29.97', label: '29.97 fps (NTSC Broadcast)' },
  { value: '30', label: '30 fps' },
  { value: '24', label: '24 fps (Cinema)' },
  { value: '23.976', label: '23.976 fps' },
];

export const SAMPLE_RATE_OPTIONS = [
  { value: '48000', label: '48 kHz (DVB Broadcast Standard)' },
  { value: '44100', label: '44.1 kHz' },
  { value: '32000', label: '32 kHz (DVB Radio)' },
  { value: '96000', label: '96 kHz (Studio Master)' },
];

export const PRESET_OPTIONS = [
  { value: 'medium', label: 'Normal Quality* (Medium)' },
  { value: 'ultrafast', label: 'Ultrafast (Lowest Latency)' },
  { value: 'superfast', label: 'Superfast' },
  { value: 'veryfast', label: 'Very Fast' },
  { value: 'faster', label: 'Faster' },
  { value: 'fast', label: 'Fast' },
  { value: 'slow', label: 'Slow (Higher Quality)' },
  { value: 'slower', label: 'Slower' },
  { value: 'veryslow', label: 'Very Slow (Maximum Compression)' },
];

export const TUNE_OPTIONS = [
  { value: '', label: 'None' },
  { value: 'hq', label: 'High Quality' },
  { value: 'll', label: 'Low Latency' },
  { value: 'zerolatency', label: 'Zero Latency (Ultra Real-Time)' },
  { value: 'film', label: 'Film (Live Action Content)' },
  { value: 'animation', label: 'Animation' },
  { value: 'grain', label: 'Grain (Preserve Film Grain)' },
  { value: 'stillimage', label: 'Still Image' },
  { value: 'fastdecode', label: 'Fast Decode' },
];

export const INTERPOLATION_OPTIONS = [
  { value: 'default', label: 'Default' },
  { value: 'bicubic', label: 'Bicubic (Standard)' },
  { value: 'bilinear', label: 'Bilinear (Fast)' },
  { value: 'lanczos', label: 'Lanczos (Sharp & High Quality)' },
  { value: 'spline', label: 'Spline' },
];

export const ASPECT_RATIO_OPTIONS = [
  { value: 'original', label: 'Original' },
  { value: '16:9', label: '16:9 (Widescreen HD)' },
  { value: '4:3', label: '4:3 (Standard Broadcast SD)' },
  { value: '21:9', label: '21:9 (Cinematic)' },
  { value: '1:1', label: '1:1 (Square)' },
];

export const FPS_MODE_OPTIONS = [
  { value: 'auto', label: 'Auto' },
  { value: 'cfr', label: 'CFR (Constant Frame Rate / Broadcast Standard)' },
  { value: 'vfr', label: 'VFR (Variable Frame Rate)' },
  { value: 'passthrough', label: 'Passthrough' },
];

export const AUDIO_CHANNELS_OPTIONS = [
  { value: 'all', label: 'All (Passthrough)' },
  { value: '2', label: 'Stereo (2.0 - FL, FR)' },
  { value: '1', label: 'Mono (1.0 - FC)' },
  { value: '6', label: '5.1 Surround (FL, FR, FC, LFE, BL, BR)' },
  { value: '4', label: '4.0 Surround' },
];

export const AUDIO_TRACK_OPTIONS = [
  { value: 'all', label: 'All' },
  { value: 'first', label: 'First' },
  { value: '0', label: 'Track 1 (Index 0)' },
  { value: '1', label: 'Track 2 (Index 1)' },
  { value: '2', label: 'Track 3 (Index 2)' },
  { value: '3', label: 'Track 4 (Index 3)' },
];

export const VIDEO_TRACK_OPTIONS = [
  { value: 'first', label: 'First' },
  { value: 'all', label: 'All' },
  { value: '0', label: 'Video 1 (Index 0)' },
  { value: '1', label: 'Video 2 (Index 1)' },
];

export const SUBTITLE_OVERLAY_OPTIONS = [
  { value: 'off', label: 'Off' },
  { value: 'dvb_sub', label: 'DVB Subtitles (DVB-SUB Passthrough)' },
  { value: 'burnin', label: 'Burn-in Hardsub' },
  { value: 'teletext', label: 'DVB Teletext Passthrough' },
];

export const AUDIO_BITRATE_OPTIONS = [
  { value: '64', label: '64 kbps (Speech/Radio)' },
  { value: '96', label: '96 kbps' },
  { value: '128', label: '128 kbps (Standard)' },
  { value: '160', label: '160 kbps' },
  { value: '192', label: '192 kbps* (DVB Broadcast Standard)' },
  { value: '224', label: '224 kbps' },
  { value: '256', label: '256 kbps (High Fidelity)' },
  { value: '320', label: '320 kbps' },
  { value: '384', label: '384 kbps (Dolby 5.1 Standard)' },
];

export const PIXEL_FORMAT_OPTIONS = [
  { value: 'default', label: 'Default' },
  { value: 'yuv420p', label: 'yuv420p (Standard 8-bit 4:2:0)' },
  { value: 'yuv422p', label: 'yuv422p (Broadcast 8-bit 4:2:2)' },
  { value: 'yuv420p10le', label: 'yuv420p10le (HDR 10-bit 4:2:0)' },
  { value: 'yuv422p10le', label: 'yuv422p10le (Master 10-bit 4:2:2)' },
  { value: 'yuv444p', label: 'yuv444p (Full RGB 4:4:4)' },
];

export const DEFAULT_DECKLINK_FORMATS: {
  code: string;
  resolution: string;
  width: number;
  height: number;
  fps: string;
  fpsNum: number;
  fpsDen: number;
  interlaced: boolean;
  fieldOrder?: string;
  description: string;
}[] = [
  { code: 'Hi50', resolution: '1920x1080', width: 1920, height: 1080, fps: '50', fpsNum: 25000, fpsDen: 1000, interlaced: true, fieldOrder: 'upper field first', description: '1080i 50 fps (1920x1080, Interlaced Upper Field - Broadcast PAL)' },
  { code: 'Hi59', resolution: '1920x1080', width: 1920, height: 1080, fps: '59.94', fpsNum: 30000, fpsDen: 1001, interlaced: true, fieldOrder: 'upper field first', description: '1080i 59.94 fps (1920x1080, Interlaced Upper Field - Broadcast NTSC)' },
  { code: 'Hi60', resolution: '1920x1080', width: 1920, height: 1080, fps: '60', fpsNum: 30000, fpsDen: 1000, interlaced: true, fieldOrder: 'upper field first', description: '1080i 60 fps (1920x1080, Interlaced Upper Field)' },
  { code: 'Hp50', resolution: '1920x1080', width: 1920, height: 1080, fps: '50', fpsNum: 50000, fpsDen: 1000, interlaced: false, description: '1080p 50 fps (1920x1080, Progressive 50 Hz)' },
  { code: 'Hp59', resolution: '1920x1080', width: 1920, height: 1080, fps: '59.94', fpsNum: 60000, fpsDen: 1001, interlaced: false, description: '1080p 59.94 fps (1920x1080, Progressive 59.94 Hz)' },
  { code: 'Hp60', resolution: '1920x1080', width: 1920, height: 1080, fps: '60', fpsNum: 60000, fpsDen: 1000, interlaced: false, description: '1080p 60 fps (1920x1080, Progressive 60 Hz)' },
  { code: 'Hp25', resolution: '1920x1080', width: 1920, height: 1080, fps: '25', fpsNum: 25000, fpsDen: 1000, interlaced: false, description: '1080p 25 fps (1920x1080, Progressive 25 Hz)' },
  { code: 'Hp29', resolution: '1920x1080', width: 1920, height: 1080, fps: '29.97', fpsNum: 30000, fpsDen: 1001, interlaced: false, description: '1080p 29.97 fps (1920x1080, Progressive 29.97 Hz)' },
  { code: 'Hp30', resolution: '1920x1080', width: 1920, height: 1080, fps: '30', fpsNum: 30000, fpsDen: 1000, interlaced: false, description: '1080p 30 fps (1920x1080, Progressive 30 Hz)' },
  { code: '24ps', resolution: '1920x1080', width: 1920, height: 1080, fps: '24', fpsNum: 24000, fpsDen: 1000, interlaced: false, description: '1080p 24 fps (1920x1080, Progressive Cinema Film)' },
  { code: '23ps', resolution: '1920x1080', width: 1920, height: 1080, fps: '23.98', fpsNum: 24000, fpsDen: 1001, interlaced: false, description: '1080p 23.98 fps (1920x1080, Progressive Film)' },
  { code: 'hp50', resolution: '1280x720', width: 1280, height: 720, fps: '50', fpsNum: 50000, fpsDen: 1000, interlaced: false, description: '720p 50 fps (1280x720, Progressive HD)' },
  { code: 'hp59', resolution: '1280x720', width: 1280, height: 720, fps: '59.94', fpsNum: 60000, fpsDen: 1001, interlaced: false, description: '720p 59.94 fps (1280x720, Progressive HD)' },
  { code: 'hp60', resolution: '1280x720', width: 1280, height: 720, fps: '60', fpsNum: 60000, fpsDen: 1000, interlaced: false, description: '720p 60 fps (1280x720, Progressive HD)' },
  { code: 'pal ', resolution: '720x576', width: 720, height: 576, fps: '25', fpsNum: 25000, fpsDen: 1000, interlaced: true, fieldOrder: 'upper field first', description: 'PAL 576i (720x576, Interlaced Upper Field - SD Broadcast)' },
  { code: 'ntsc', resolution: '720x486', width: 720, height: 486, fps: '29.97', fpsNum: 30000, fpsDen: 1001, interlaced: true, fieldOrder: 'lower field first', description: 'NTSC 486i (720x486, Interlaced Lower Field - SD Broadcast)' },
  { code: '4k50', resolution: '3840x2160', width: 3840, height: 2160, fps: '50', fpsNum: 50000, fpsDen: 1000, interlaced: false, description: '4K UHD 50 fps (3840x2160, Progressive Ultra HD)' },
  { code: '4k59', resolution: '3840x2160', width: 3840, height: 2160, fps: '59.94', fpsNum: 60000, fpsDen: 1001, interlaced: false, description: '4K UHD 59.94 fps (3840x2160, Progressive Ultra HD)' },
  { code: '4k60', resolution: '3840x2160', width: 3840, height: 2160, fps: '60', fpsNum: 60000, fpsDen: 1000, interlaced: false, description: '4K UHD 60 fps (3840x2160, Progressive Ultra HD)' },
  { code: '4k25', resolution: '3840x2160', width: 3840, height: 2160, fps: '25', fpsNum: 25000, fpsDen: 1000, interlaced: false, description: '4K UHD 25 fps (3840x2160, Progressive 25 Hz)' },
  { code: '4k30', resolution: '3840x2160', width: 3840, height: 2160, fps: '30', fpsNum: 30000, fpsDen: 1000, interlaced: false, description: '4K UHD 30 fps (3840x2160, Progressive 30 Hz)' },
  { code: '4k24', resolution: '3840x2160', width: 3840, height: 2160, fps: '24', fpsNum: 24000, fpsDen: 1000, interlaced: false, description: '4K UHD 24 fps (3840x2160, Progressive Cinema Film)' },
  { code: '4k23', resolution: '3840x2160', width: 3840, height: 2160, fps: '23.98', fpsNum: 24000, fpsDen: 1001, interlaced: false, description: '4K UHD 23.98 fps (3840x2160, Progressive Film)' },
];

export const AVC_PROFILE_OPTIONS = [
  { value: 'high', label: 'High Profile (Broadcast Standard)' },
  { value: 'main', label: 'Main Profile (Standard)' },
  { value: 'baseline', label: 'Baseline Profile (Compatibility)' },
  { value: 'high10', label: 'High 10 (10-bit Color)' },
  { value: 'high422', label: 'High 4:2:2 (Production Quality)' },
  { value: 'high444', label: 'High 4:4:4 (Mastering RGB)' },
];

export const AVC_LEVEL_OPTIONS = [
  { value: 'auto', label: 'Auto (Recommended)' },
  { value: '3.0', label: 'Level 3.0 (SD / 720x480)' },
  { value: '3.1', label: 'Level 3.1 (720p30)' },
  { value: '3.2', label: 'Level 3.2 (720p60)' },
  { value: '4.0', label: 'Level 4.0 (1080p30)' },
  { value: '4.1', label: 'Level 4.1 (1080i50 / 1080i60 / 1080p30 Broadcast)' },
  { value: '4.2', label: 'Level 4.2 (1080p60)' },
  { value: '5.0', label: 'Level 5.0 (2K / High Bitrate)' },
  { value: '5.1', label: 'Level 5.1 (4K UHD 30fps)' },
  { value: '5.2', label: 'Level 5.2 (4K UHD 60fps)' },
];

export const RATE_CONTROL_OPTIONS = [
  { value: 'cbr', label: 'CBR — Constant Bitrate (Strict Broadcast DVB)' },
  { value: 'vbr', label: 'VBR — Variable Bitrate (Bounded Peak)' },
  { value: 'crf', label: 'CRF — Constant Rate Factor (Quality Target)' },
  { value: 'cqp', label: 'CQP — Constant Quantization Parameter' },
];

export const NIC_BONDING_MODES = [
  { value: 'balance-rr', label: 'Round-Robin (balance-rr / Mode 0)' },
  { value: 'active-backup', label: 'Active-Backup (Fault Tolerance / Mode 1)' },
  { value: 'balance-xor', label: 'XOR Load Balancing (balance-xor / Mode 2)' },
  { value: 'broadcast', label: 'Broadcast (Redundant / Mode 3)' },
  { value: '802.3ad', label: 'IEEE 802.3ad LACP (Dynamic Link Aggregation / Mode 4)' },
  { value: 'balance-tlb', label: 'Adaptive Transmit Load Balancing (balance-tlb / Mode 5)' },
  { value: 'balance-alb', label: 'Adaptive Load Balancing (balance-alb / Mode 6)' },
];

export const DEFAULT_ALARM_RULES = [
  { id: 'alarm-output-links-down', name: 'All Output Links Down', enabled: true, sendTrap: true, severity: 'critical', timeoutMs: 0 },
  { id: 'alarm-audio-fallback', name: 'Audio Signal Fallback', enabled: true, sendTrap: true, severity: 'warning', timeoutMs: 0 },
  { id: 'alarm-audio-invalid', name: 'Audio Signal Invalid', enabled: true, sendTrap: true, severity: 'warning', timeoutMs: 2000 },
  { id: 'alarm-audio-missing', name: 'Audio Signal Missing', enabled: true, sendTrap: true, severity: 'warning', timeoutMs: 2000 },
  { id: 'alarm-audio-silent', name: 'Audio Signal Silent', enabled: true, sendTrap: true, severity: 'warning', timeoutMs: 2000 },
  { id: 'alarm-data-missing', name: 'Data Signal Missing', enabled: true, sendTrap: true, severity: 'warning', timeoutMs: 2000 },
  { id: 'alarm-dolby-error', name: 'Dolby Decoding Error', enabled: true, sendTrap: true, severity: 'warning', timeoutMs: 1000 },
  { id: 'alarm-esam-comm', name: 'ESAM Server Communication Issue', enabled: true, sendTrap: true, severity: 'warning', timeoutMs: 0 },
  { id: 'alarm-video-freeze', name: 'Video Freeze / Loss of Input Signal', enabled: true, sendTrap: true, severity: 'critical', timeoutMs: 3000 },
  { id: 'alarm-decklink-drop', name: 'DeckLink Frame Drop / Underflow', enabled: true, sendTrap: true, severity: 'warning', timeoutMs: 1000 },
  { id: 'alarm-ps-redundancy', name: 'Power Supply Redundancy Lost', enabled: true, sendTrap: true, severity: 'critical', timeoutMs: 1000 },
  { id: 'alarm-storage-critical', name: 'Master Recording Storage Space Critical', enabled: true, sendTrap: true, severity: 'critical', timeoutMs: 5000 },
  { id: 'alarm-cpu-overheat', name: 'CPU / Transcode Engine Thermal Warning', enabled: true, sendTrap: true, severity: 'warning', timeoutMs: 10000 },
];


