import { TranscodingProfile, VideoCodec, AudioCodec, Protocol } from './types';

export const DEFAULT_PROFILES: TranscodingProfile[] = [
  {
    id: 'low-cpu-720p',
    name: 'Low CPU 720p (UDP Stable)',
    videoCodec: VideoCodec.H264,
    audioCodec: AudioCodec.AAC,
    resolution: '1280x720',
    videoQualityMode: 'bitrate',
    videoBitrate: 2000,
    audioBitrate: 128,
    sampleRate: 48000,
    preset: 'ultrafast',
    framerate: 25,
    pixelFormat: 'yuv420p',
  },
  // ADDED: Profile for HTTP-TS based on your working command
  {
    id: 'live-http-ts-1',
    name: 'HTTP-TS: 720p Low Latency',
    videoCodec: VideoCodec.H264,
    videoQualityMode: 'bitrate',
    videoBitrate: 2000,
    maxrate: 2000,
    bufsize: 4000,
    resolution: '1280x720',
    framerate: 30,
    preset: 'ultrafast',
    tune: 'zerolatency',
    pixelFormat: 'yuv420p',
    audioCodec: AudioCodec.AAC,
    audioBitrate: 128,
    sampleRate: 48000,
  },
  {
    id: 'default-h264-1080p',
    name: 'H.264 1080p (Software)',
    videoCodec: VideoCodec.H264,
    audioCodec: AudioCodec.AAC,
    resolution: '1920x1080',
    videoQualityMode: 'bitrate',
    videoBitrate: 4000,
    audioBitrate: 128,
    sampleRate: 48000,
    preset: 'medium',
    framerate: 30,
    pixelFormat: 'yuv420p',
  },
  {
    id: 'nvidia-h264-1080p',
    name: 'H.264 1080p (NVIDIA NVENC)',
    videoCodec: VideoCodec.H264_NVENC,
    audioCodec: AudioCodec.AAC,
    resolution: '1920x1080',
    videoQualityMode: 'bitrate',
    videoBitrate: 4000,
    audioBitrate: 128,
    sampleRate: 48000,
    preset: 'p4',
    framerate: 30,
    pixelFormat: 'yuv420p',
  },
  {
    id: 'amd-h264-1080p',
    name: 'H.264 1080p (AMD AMF)',
    videoCodec: VideoCodec.H264_AMF,
    audioCodec: AudioCodec.AAC,
    resolution: '1920x1080',
    videoQualityMode: 'bitrate',
    videoBitrate: 4000,
    audioBitrate: 128,
    sampleRate: 48000,
    preset: 'p4',
    framerate: 30,
    pixelFormat: 'yuv420p',
  },
  {
    id: 'amd-hevc-1080p',
    name: 'HEVC 1080p (AMD AMF)',
    videoCodec: VideoCodec.HEVC_AMF,
    audioCodec: AudioCodec.AAC,
    resolution: '1920x1080',
    videoQualityMode: 'bitrate',
    videoBitrate: 6000,
    audioBitrate: 128,
    sampleRate: 48000,
    preset: 'p4',
    framerate: 30,
    pixelFormat: 'yuv420p',
  },
  {
    id: 'apple-h264-1080p',
    name: 'H.264 1080p (Apple VideoToolbox)',
    videoCodec: VideoCodec.H264_VIDEOTOOLBOX,
    audioCodec: AudioCodec.AAC,
    resolution: '1920x1080',
    videoQualityMode: 'bitrate',
    videoBitrate: 4000,
    audioBitrate: 128,
    sampleRate: 48000,
    preset: 'ultrafast',
    framerate: 30,
    pixelFormat: 'yuv420p',
  },
  {
    id: 'quality-h264-crf-23',
    name: 'High-Quality H.264 (CRF 23)',
    videoCodec: VideoCodec.H264,
    audioCodec: AudioCodec.AAC,
    resolution: '1920x1080',
    videoQualityMode: 'crf',
    crf: 23,
    audioBitrate: 192,
    sampleRate: 48000,
    preset: 'medium',
    framerate: 30,
    pixelFormat: 'yuv420p',
  },
  {
    id: 'uhd-h265-4k',
    name: 'UHD HEVC 4K (Software)',
    videoCodec: VideoCodec.H265,
    audioCodec: AudioCodec.AAC,
    resolution: '3840x2160',
    videoQualityMode: 'bitrate',
    videoBitrate: 15000,
    audioBitrate: 192,
    sampleRate: 48000,
    preset: 'medium',
    framerate: 30,
    pixelFormat: 'yuv420p',
  },
  {
    id: 'audio-only-aac',
    name: 'Audio Only (AAC 128k)',
    videoCodec: VideoCodec.Copy,
    audioCodec: AudioCodec.AAC,
    resolution: 'N/A',
    videoQualityMode: 'bitrate',
    isAudioOnly: true,
    audioBitrate: 128,
    sampleRate: 48000,
  },
  {
    id: 'passthrough-copy',
    name: 'Passthrough (Stream Copy)',
    videoCodec: VideoCodec.Copy,
    audioCodec: AudioCodec.Copy,
    resolution: 'N/A',
    videoQualityMode: 'bitrate',
  },
];

export const VIDEO_CODEC_OPTIONS = [
  { value: 'header-software', label: '--- Software (CPU) ---', disabled: true },
  { value: VideoCodec.H264, label: 'H.264 (libx264)' },
  { value: VideoCodec.H265, label: 'HEVC (libx265)' },
  { value: VideoCodec.VP9, label: 'VP9 (libvpx-vp9)' },
  { value: VideoCodec.AV1, label: 'AV1 (libaom-av1)' },
  { value: 'header-nvidia', label: '--- NVIDIA (NVENC) ---', disabled: true },
  { value: VideoCodec.H264_NVENC, label: 'H.264 (h264_nvenc)' },
  { value: VideoCodec.HEVC_NVENC, label: 'HEVC (hevc_nvenc)' },
  { value: 'header-amd', label: '--- AMD (AMF) ---', disabled: true },
  { value: VideoCodec.H264_AMF, label: 'H.264 (h264_amf)' },
  { value: VideoCodec.HEVC_AMF, label: 'HEVC (hevc_amf)' },
  { value: 'header-apple', label: '--- Apple (VideoToolbox) ---', disabled: true },
  { value: VideoCodec.H264_VIDEOTOOLBOX, label: 'H.264 (h264_videotoolbox)' },
  { value: VideoCodec.HEVC_VIDEOTOOLBOX, label: 'HEVC (hevc_videotoolbox)' },
  { value: 'header-other', label: '--- Other ---', disabled: true },
  { value: VideoCodec.Copy, label: 'Copy (Passthrough)' },
];

export const AUDIO_CODEC_OPTIONS = [
  { value: AudioCodec.AAC, label: 'AAC' },
  { value: AudioCodec.Opus, label: 'Opus' },
  { value: AudioCodec.MP3, label: 'MP3' },
  { value: AudioCodec.Copy, label: 'Copy (Passthrough)' },
];

export const RESOLUTION_OPTIONS = [
  { value: 'source', label: 'Source / Original (Auto)' },
  { value: '3840x2160', label: '4K UHD (3840x2160)' },
  { value: '2560x1440', label: '2K QHD (2560x1440)' },
  { value: '1920x1080', label: 'Full HD 1080p (1920x1080)' },
  { value: '1280x720', label: 'HD 720p (1280x720)' },
  { value: '720x576', label: 'PAL 576i/p (720x576)' },
  { value: '720x480', label: 'NTSC 480i/p (720x480)' },
  { value: '854x480', label: 'SD 480p (854x480)' },
];

export const LIVE_PROTOCOL_OPTIONS = [
  { value: Protocol.HLS, label: 'HLS (HTTP Live Streaming)' },
  { value: Protocol.DASH, label: 'DASH (Dynamic Adaptive Streaming)' },
  { value: Protocol.RTMP, label: 'RTMP (Real-Time Messaging Protocol)' },
  { value: Protocol.SRT, label: 'SRT (Secure Reliable Transport)' },
  { value: Protocol.UDP, label: 'UDP (User Datagram Protocol)' },
  { value: Protocol.HTTP_TS, label: 'HTTP-TS (MPEG-TS over HTTP)' },
  { value: Protocol.RECORDING, label: 'Recording File' },
];

export const FRAMERATE_OPTIONS = [
  { value: '0', label: 'Source / Pass-through (Auto)' },
  { value: '50', label: '50 fps (Broadcast PAL/HD Standard)' },
  { value: '59.94', label: '59.94 fps (Broadcast NTSC/HD Standard)' },
  { value: '60', label: '60 fps' },
  { value: '25', label: '25 fps (PAL Broadcast)' },
  { value: '29.97', label: '29.97 fps (NTSC Broadcast)' },
  { value: '30', label: '30 fps' },
  { value: '24', label: '24 fps (Cinema)' },
  { value: '23.976', label: '23.976 fps' },
];

export const SAMPLE_RATE_OPTIONS = [
  { value: '44100', label: '44.1 kHz' },
  { value: '48000', label: '48 kHz' },
];

export const PRESET_OPTIONS = [
  { value: 'ultrafast', label: 'Ultrafast' },
  { value: 'superfast', label: 'Superfast' },
  { value: 'veryfast', label: 'Veryfast' },
  { value: 'faster', label: 'Faster' },
  { value: 'fast', label: 'Fast' },
  { value: 'medium', label: 'Medium' },
  { value: 'slow', label: 'Slow' },
  { value: 'slower', label: 'Slower' },
  { value: 'veryslow', label: 'Veryslow' },
];

export const PIXEL_FORMAT_OPTIONS = [
  { value: 'yuv420p', label: 'yuv420p' },
  { value: 'yuv422p', label: 'yuv422p' },
  { value: 'yuv444p', label: 'yuv444p' },
];
